services:
    app:
        build: .
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /Ecommerce-Website-Laravel
        volumes:
            - '.:/Ecommerce-Website-Laravel'
        ports:
            - '8000:8000'
        command: "bash -c \"\n  composer install --no-interaction &&\n  until php artisan migrate --force; do\n  echo 'Waiting for MySQL...';\n  sleep 2;\n  done &&\n  php artisan serve --host=0.0.0.0 --port=8000\n\"\n"
        networks:
            - app-network
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        container_name: mysql_container
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ecommerceLrvl
            MYSQL_USER: ecommerce
            MYSQL_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - '3306:3306'
        volumes:
            - 'db_data:/var/lib/mysql'
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    db_data: null
    sail-mysql:
        driver: local
